# Generated by Django 4.2.3 on 2023-08-01 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0002_user_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='posts',
            new_name='favorites',
        ),
    ]
